export const LecturasArr = [
  {
    icono: 'lectura',
    tipo: 'LECTURA',
    titulo: 'Cuentos para aprender ortografia',
    nuevo: true,
    demorado: false,
    fechaEntrega: '15 de Abril',
    progreso: 25,
    materia: 'Lengua',
  },
  {
    icono: 'lectura',
    tipo: 'LECTURA',
    titulo: 'Cuentos para aprender ortografia',
    nuevo: true,
    demorado: false,
    fechaEntrega: '15 de Abril',
    progreso: 100,
    materia: 'Lengua',
  },
  {
    icono: 'lectura',
    tipo: 'LECTURA',
    titulo: 'Cuentos para aprender ortografia',
    nuevo: true,
    demorado: false,
    fechaEntrega: '15 de Abril',
    progreso: 100,
    materia: 'Lengua',
  },
  {
    icono: 'lectura',
    tipo: 'LECTURA',
    titulo: 'Cuentos para aprender ortografia',
    nuevo: true,
    demorado: false,
    fechaEntrega: '15 de Abril',
    progreso: 0,
    materia: 'Lengua',
  },
];

export const ActividadesArr = [
  {
    icono: 'actividad',
    tipo: 'ACTIVIDAD CON PREGUNTAS',
    titulo: '¿Qué es la potencia y la raiz cuadrada de un número?',
    nuevo: false,
    demorado: true,
    fechaEntrega: '15 de Abril',
    progreso: 25,
    esperandoCorreccion: false,
    materia: 'Fisica',
  },
  {
    icono: 'actividad',
    tipo: 'ACTIVIDAD CON PREGUNTAS',
    titulo: '¿Qué es la potencia y la raiz cuadrada de un número?',
    nuevo: false,
    demorado: true,
    fechaEntrega: '15 de Abril',
    progreso: 25,
    esperandoCorreccion: false,
    materia: 'Fisica',
  },
];
